//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public string skills { get; set; }
        public int salary { get; set; }
        public int depid { get; set; }
    
        public virtual department department { get; set; }
    }
}
